# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: OpenSeizureDetector

# Short description (goes below the title; it will also be used in the RSS feed)
description: OpenSeizureDetector is a system to detect and alarm epileptic seizures without contact with the patient or bed etc.  See <a href="https://github.com/jones139/OpenSeizureDetector/">Github Repository</a> for source code.  

# Your name, as you want it to appear underneath each post and in the footer
author: Graham Jones

# Your email if you want it to be linked on the contact page
author_email: grahamjones139+osd@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: /OpenSeizureDetector 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://openseizuredetector.org.uk/OpenSeizureDetector

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules]
